// @ts-nocheck
import * as __fd_glob_57 from "../content/docs/using-the-app/portfolio/performance-and-history.mdx?collection=docs"
import * as __fd_glob_56 from "../content/docs/using-the-app/portfolio/multi-asset.mdx?collection=docs"
import * as __fd_glob_55 from "../content/docs/using-the-app/portfolio/index.mdx?collection=docs"
import * as __fd_glob_54 from "../content/docs/using-the-app/farming/smart-wallet-mode.mdx?collection=docs"
import * as __fd_glob_53 from "../content/docs/using-the-app/farming/index.mdx?collection=docs"
import * as __fd_glob_52 from "../content/docs/using-the-app/farming/deposit-mode.mdx?collection=docs"
import * as __fd_glob_51 from "../content/docs/using-the-app/farming/custom-mode.mdx?collection=docs"
import * as __fd_glob_50 from "../content/docs/using-the-app/chat/soroswap.mdx?collection=docs"
import * as __fd_glob_49 from "../content/docs/using-the-app/chat/sdex.mdx?collection=docs"
import * as __fd_glob_48 from "../content/docs/using-the-app/chat/research.mdx?collection=docs"
import * as __fd_glob_47 from "../content/docs/using-the-app/chat/phoenix.mdx?collection=docs"
import * as __fd_glob_46 from "../content/docs/using-the-app/chat/index.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/using-the-app/chat/defindex.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/using-the-app/chat/blend.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/using-the-app/chat/aquarius.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/using-the-app/chat/allbridge.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/using-the-app/aggregate/swap.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/using-the-app/aggregate/index.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/using-the-app/aggregate/bridge.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/trust-and-safety/what-the-bot-can-do.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/trust-and-safety/risks.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/trust-and-safety/privacy.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/trust-and-safety/index.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/trust-and-safety/audits-and-addresses.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/using-the-app/prompt-recipes.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/using-the-app/index.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/reference/troubleshooting.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/reference/sdk.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/reference/roadmap.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/reference/index.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/reference/glossary.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/reference/faq.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/reference/changelog.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/introduction/what-and-why.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/introduction/supported.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/introduction/index.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/how-it-works/vaults-and-presets.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/how-it-works/strategies.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/how-it-works/rebalance-engine.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/how-it-works/index.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/how-it-works/fees-and-yield.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/how-it-works/ai-and-tools.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/getting-started/set-up-wallet.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/getting-started/see-it-working.mdx?collection=docs"
import * as __fd_glob_13 from "../content/docs/getting-started/index.mdx?collection=docs"
import * as __fd_glob_12 from "../content/docs/getting-started/create-and-fund-vault.mdx?collection=docs"
import * as __fd_glob_11 from "../content/docs/index.mdx?collection=docs"
import { default as __fd_glob_10 } from "../content/docs/using-the-app/portfolio/meta.json?collection=docs"
import { default as __fd_glob_9 } from "../content/docs/using-the-app/chat/meta.json?collection=docs"
import { default as __fd_glob_8 } from "../content/docs/using-the-app/farming/meta.json?collection=docs"
import { default as __fd_glob_7 } from "../content/docs/using-the-app/aggregate/meta.json?collection=docs"
import { default as __fd_glob_6 } from "../content/docs/how-it-works/meta.json?collection=docs"
import { default as __fd_glob_5 } from "../content/docs/using-the-app/meta.json?collection=docs"
import { default as __fd_glob_4 } from "../content/docs/reference/meta.json?collection=docs"
import { default as __fd_glob_3 } from "../content/docs/introduction/meta.json?collection=docs"
import { default as __fd_glob_2 } from "../content/docs/trust-and-safety/meta.json?collection=docs"
import { default as __fd_glob_1 } from "../content/docs/getting-started/meta.json?collection=docs"
import { default as __fd_glob_0 } from "../content/docs/meta.json?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "content/docs", {"meta.json": __fd_glob_0, "getting-started/meta.json": __fd_glob_1, "trust-and-safety/meta.json": __fd_glob_2, "introduction/meta.json": __fd_glob_3, "reference/meta.json": __fd_glob_4, "using-the-app/meta.json": __fd_glob_5, "how-it-works/meta.json": __fd_glob_6, "using-the-app/aggregate/meta.json": __fd_glob_7, "using-the-app/farming/meta.json": __fd_glob_8, "using-the-app/chat/meta.json": __fd_glob_9, "using-the-app/portfolio/meta.json": __fd_glob_10, }, {"index.mdx": __fd_glob_11, "getting-started/create-and-fund-vault.mdx": __fd_glob_12, "getting-started/index.mdx": __fd_glob_13, "getting-started/see-it-working.mdx": __fd_glob_14, "getting-started/set-up-wallet.mdx": __fd_glob_15, "how-it-works/ai-and-tools.mdx": __fd_glob_16, "how-it-works/fees-and-yield.mdx": __fd_glob_17, "how-it-works/index.mdx": __fd_glob_18, "how-it-works/rebalance-engine.mdx": __fd_glob_19, "how-it-works/strategies.mdx": __fd_glob_20, "how-it-works/vaults-and-presets.mdx": __fd_glob_21, "introduction/index.mdx": __fd_glob_22, "introduction/supported.mdx": __fd_glob_23, "introduction/what-and-why.mdx": __fd_glob_24, "reference/changelog.mdx": __fd_glob_25, "reference/faq.mdx": __fd_glob_26, "reference/glossary.mdx": __fd_glob_27, "reference/index.mdx": __fd_glob_28, "reference/roadmap.mdx": __fd_glob_29, "reference/sdk.mdx": __fd_glob_30, "reference/troubleshooting.mdx": __fd_glob_31, "using-the-app/index.mdx": __fd_glob_32, "using-the-app/prompt-recipes.mdx": __fd_glob_33, "trust-and-safety/audits-and-addresses.mdx": __fd_glob_34, "trust-and-safety/index.mdx": __fd_glob_35, "trust-and-safety/privacy.mdx": __fd_glob_36, "trust-and-safety/risks.mdx": __fd_glob_37, "trust-and-safety/what-the-bot-can-do.mdx": __fd_glob_38, "using-the-app/aggregate/bridge.mdx": __fd_glob_39, "using-the-app/aggregate/index.mdx": __fd_glob_40, "using-the-app/aggregate/swap.mdx": __fd_glob_41, "using-the-app/chat/allbridge.mdx": __fd_glob_42, "using-the-app/chat/aquarius.mdx": __fd_glob_43, "using-the-app/chat/blend.mdx": __fd_glob_44, "using-the-app/chat/defindex.mdx": __fd_glob_45, "using-the-app/chat/index.mdx": __fd_glob_46, "using-the-app/chat/phoenix.mdx": __fd_glob_47, "using-the-app/chat/research.mdx": __fd_glob_48, "using-the-app/chat/sdex.mdx": __fd_glob_49, "using-the-app/chat/soroswap.mdx": __fd_glob_50, "using-the-app/farming/custom-mode.mdx": __fd_glob_51, "using-the-app/farming/deposit-mode.mdx": __fd_glob_52, "using-the-app/farming/index.mdx": __fd_glob_53, "using-the-app/farming/smart-wallet-mode.mdx": __fd_glob_54, "using-the-app/portfolio/index.mdx": __fd_glob_55, "using-the-app/portfolio/multi-asset.mdx": __fd_glob_56, "using-the-app/portfolio/performance-and-history.mdx": __fd_glob_57, });